/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
Traceback (most recent call last):
  File "tools/train.py", line 180, in <module>
    main()
  File "tools/train.py", line 155, in main
    runner = Runner.from_cfg(cfg)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 445, in from_cfg
    runner = cls(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 355, in __init__
    self.setup_env(env_cfg)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 658, in setup_env
    init_dist(self.launcher, **dist_cfg)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/dist/utils.py", line 84, in init_dist
    _init_dist_pytorch(backend, init_backend=init_backend, **kwargs)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/dist/utils.py", line 122, in _init_dist_pytorch
    torch.cuda.set_device(local_rank)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/cuda/__init__.py", line 313, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3703693 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 3703694) of binary: /home/nr4325/miniconda3/envs/pose4/bin/python
Traceback (most recent call last):
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-02-01_07:16:35
  host      : skl-a-48.rc.rit.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3703694)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
