/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
Traceback (most recent call last):
  File "tools/train.py", line 162, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 162, in <module>
    main()
  File "tools/train.py", line 158, in main
    runner.train()
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1745, in train
    main()
  File "tools/train.py", line 158, in main
    runner.train()
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1745, in train
        model = self.train_loop.run()  # type: ignoremodel = self.train_loop.run()  # type: ignore

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
        self.run_epoch()self.run_epoch()

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
      File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/loops.py", line 128, in run_iter
self.run_iter(idx, data_batch)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
      File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 121, in train_step
outputs = self.runner.model.train_step(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 121, in train_step
        losses = self._run_forward(data, mode='loss')losses = self._run_forward(data, mode='loss')

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 161, in _run_forward
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 161, in _run_forward
        results = self(**data, mode=mode)results = self(**data, mode=mode)

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)    
return forward_call(*input, **kwargs)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
        output = self.module(*inputs[0], **kwargs[0])output = self.module(*inputs[0], **kwargs[0])

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
        return forward_call(*input, **kwargs)return forward_call(*input, **kwargs)

  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/pose_estimators/base.py", line 136, in forward
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/pose_estimators/base.py", line 136, in forward
    return self.loss(inputs, data_samples)
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/pose_estimators/topdown.py", line 76, in loss
    return self.loss(inputs, data_samples)
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/pose_estimators/topdown.py", line 76, in loss
        feats = self.extract_feat(inputs)feats = self.extract_feat(inputs)

  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/pose_estimators/base.py", line 188, in extract_feat
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/pose_estimators/base.py", line 188, in extract_feat
    x = self.backbone(inputs)    
x = self.backbone(inputs)  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
      File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/backbones/wtpose_swinv1_wtm3a.py", line 1428, in forward
return forward_call(*input, **kwargs)
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/backbones/wtpose_swinv1_wtm3a.py", line 1428, in forward
    x = self.wtm3d(outs, resnet_out)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    x = self.wtm3d(outs, resnet_out)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/backbones/wtpose_swinv1_wtm3a.py", line 600, in forward
    return forward_call(*input, **kwargs)
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/backbones/wtpose_swinv1_wtm3a.py", line 600, in forward
    x1 = self.wtb1_0(x)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    x1 = self.wtb1_0(x)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/backbones/wtpose_swinv1_wtm3a.py", line 493, in forward
    return forward_call(*input, **kwargs)
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/backbones/wtpose_swinv1_wtm3a.py", line 493, in forward
    x = self.forward_part1(x)
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/backbones/wtpose_swinv1_wtm3a.py", line 474, in forward_part1
    x = self.forward_part1(x)
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/backbones/wtpose_swinv1_wtm3a.py", line 474, in forward_part1
    x = self.norm1(x)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    x = self.norm1(x)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 189, in forward
    return forward_call(*input, **kwargs)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 189, in forward
    return F.layer_norm(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/functional.py", line 2486, in layer_norm
    return F.layer_norm(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/nn/functional.py", line 2486, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Given normalized_shape=[128], expected input with shape [*, 128], but got input of size[32, 128, 64, 48, 1]
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Given normalized_shape=[128], expected input with shape [*, 128], but got input of size[32, 128, 64, 48, 1]
/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 6234) of binary: /home/nr4325/miniconda3/envs/pose4/bin/python
Traceback (most recent call last):
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-12-22_22:04:22
  host      : skl-a-48.rc.rit.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 6235)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-22_22:04:22
  host      : skl-a-48.rc.rit.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 6234)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
