Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 143, in main
    cfg = Config.fromfile(args.config)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/config/config.py", line 456, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/config/config.py", line 940, in _file2dict
    raise e
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/config/config.py", line 918, in _file2dict
    eval(codeobj, global_locals_var, global_locals_var)
  File "/home/nr4325/Desktop/Pose4/mmpose/configs/body_2d_keypoint/topdown_heatmap/coco_aic/aa_WTPose_SwinV2_b_w8_coco_aic_256x256_1k.py", line 238, in <module>
    ann_file=data_root + 'annotations/person_keypoints_val2017.json')
NameError: name 'data_root' is not defined
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 143, in main
    cfg = Config.fromfile(args.config)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/config/config.py", line 456, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/config/config.py", line 940, in _file2dict
    raise e
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/config/config.py", line 918, in _file2dict
    eval(codeobj, global_locals_var, global_locals_var)
  File "/home/nr4325/Desktop/Pose4/mmpose/configs/body_2d_keypoint/topdown_heatmap/coco_aic/aa_WTPose_SwinV2_b_w8_coco_aic_256x256_1k.py", line 238, in <module>
    ann_file=data_root + 'annotations/person_keypoints_val2017.json')
NameError: name 'data_root' is not defined
/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 20915) of binary: /home/nr4325/miniconda3/envs/pose4/bin/python
Traceback (most recent call last):
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-09-17_19:41:27
  host      : skl-a-48.rc.rit.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 20916)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-17_19:41:27
  host      : skl-a-48.rc.rit.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 20915)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
